name: question_kitchen
description: An app to aid in my studies

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.8.0
  cloud_firestore: ^2.5.4
  hooks_riverpod: ^0.14.0+5
  riverpod: ^0.14.0+3
  freezed: ^0.14.5
  freezed_annotation: ^0.14.3
  http: ^0.13.4
  uuid: ^3.0.5
  file_saver: ^0.0.10
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0
  google_fonts: ^2.1.0
  flutter_screenutil: ^5.0.0+2
  firebase_auth: ^3.1.4
  flutter_login: ^2.2.1
  easy_debounce: ^2.0.1
  file_picker: ^4.2.0
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
